=== Barzov-Pavel/by.epam.barzov.lab3/src/xml/medicines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <element name="medicines">
        <complexType>
            <sequence>

                <element name="medicine" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="group" type="string"/>
                            <element name="analogs" type="string" maxOccurs="unbounded"/>
                            <element name="versions" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="pharm" maxOccurs="unbounded">
                                            <complexType>
                                                <sequence>
                                                    <element name="certificate">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="startDate" type="string"/>
                                                                <element name="expirationDate" type="string"/>
                                                                <element name="registrationOrganization" type="string"/>
                                                            </sequence>
                                                            <attribute name="id" type="int" use="required"/>
                                                        </complexType>
                                                    </element>

                                                    <element name="package">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="type">
                                                                    <simpleType>
                                                                        <restriction base="string">
                                                                            <enumeration value="BLISTER"/>
                                                                            <enumeration value="AMPULE"/>
                                                                            <enumeration value="BOTTLE"/>
                                                                            <enumeration value="BOX"/>
                                                                            <enumeration value="VIAL"/>
                                                                            <enumeration value="TUBE"/>
                                                                        </restriction>
                                                                    </simpleType>
                                                                </element>
                                                                <element name="amount" type="int"/>
                                                                <element name="price" type="long"/>
                                                            </sequence>
                                                        </complexType>
                                                    </element>

                                                    <element name="dosage">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="number" type="byte"/>
                                                                <element name="periodicity" type="byte"/>
                                                            </sequence>
                                                        </complexType>
                                                    </element>

                                                </sequence>
                                                <attribute name="name" type="string" use="required"/>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="version">
                                        <simpleType>
                                            <restriction base="string">
                                                <enumeration value="TABLET"/>
                                                <enumeration value="CAPSULE"/>
                                                <enumeration value="LIQUID"/>
                                                <enumeration value="POWDERS"/>
                                                <enumeration value="GRANULES"/>
                                                <enumeration value="GEL"/>
                                                <enumeration value="GAS"/>
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="name" type="string" use="required"/>
                    </complexType>
                </element>

            </sequence>
        </complexType>
    </element>
</schema>

=== Barzov-Pavel/by.epam.barzov.lab3/src/xml/medicinesWriter.xml
<?xml version="1.0" encoding="UTF-8"?><medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="./medicines.xsd"><medicine name="Flagyl"><group><![CDATA[antibiotic]]></group><analogs><![CDATA[Metronidazole]]></analogs><analogs><![CDATA[Abozole]]></analogs><analogs><![CDATA[Ambizole]]></analogs><versions version="TABLET"><pharm name="Pfizer"><certificate id="789"><startDate><![CDATA[1970-03-15]]></startDate><expirationDate><![CDATA[2025-03-15]]></expirationDate><registrationOrganization><![CDATA[FDA]]></registrationOrganization></certificate><package><type><![CDATA[BLISTER]]></type><amount><![CDATA[50]]></amount><price><![CDATA[45800]]></price></package><dosage><number><![CDATA[1]]></number><periodicity><![CDATA[2]]></periodicity></dosage></pharm><pharm name="PLIVA"><certificate id="15620"><startDate><![CDATA[1980-03-15]]></startDate><expirationDate><![CDATA[2030-03-15]]></expirationDate><registrationOrganization><![CDATA[FDA]]></registrationOrganization></certificate><package><type><![CDATA[BLISTER]]></type><amount><![CDATA[25]]></amount><price><![CDATA[25600]]></price></package><dosage><number><![CDATA[1]]></number><periodicity><![CDATA[3]]></periodicity></dosage></pharm></versions><versions version="CAPSULE"><pharm name="PLIVA"><certificate id="15619"><startDate><![CDATA[1980-03-15]]></startDate><expirationDate><![CDATA[2030-03-15]]></expirationDate><registrationOrganization><![CDATA[FDA]]></registrationOrganization></certificate><package><type><![CDATA[BLISTER]]></type><amount><![CDATA[50]]></amount><price><![CDATA[25600]]></price></package><dosage><number><![CDATA[2]]></number><periodicity><![CDATA[2]]></periodicity></dosage></pharm></versions></medicine><medicine name="Valium"><group><![CDATA[benzodiazepine]]></group><analogs><![CDATA[Diazepam]]></analogs><versions version="TABLET"><pharm name="Roche"><certificate id="123"><startDate><![CDATA[1960-01-25]]></startDate><expirationDate><![CDATA[2025-01-25]]></expirationDate><registrationOrganization><![CDATA[American Medical Association]]></registrationOrganization></certificate><package><type><![CDATA[BLISTER]]></type><amount><![CDATA[50]]></amount><price><![CDATA[25000]]></price></package><dosage><number><![CDATA[1]]></number><periodicity><![CDATA[4]]></periodicity></dosage></pharm></versions></medicine></medicines>

=== Barzov-Pavel/by.epam.barzov.lab3/src/xml/medicines.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicines xsi:schemaLocation="./medicines.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <medicine name="Valium">
        <group>benzodiazepine</group>
        <analogs>Diazepam</analogs>
        <versions version="TABLET">
            <pharm name="Roche">
                <certificate id="123">
                    <startDate>1960-01-25</startDate>
                    <expirationDate>2025-01-25</expirationDate>
                    <registrationOrganization>American Medical Association</registrationOrganization>
                </certificate>
                <package>
                    <type>BLISTER</type>
                    <amount>50</amount>
                    <price>25000</price>
                </package>
                <dosage>
                    <number>1</number>
                    <periodicity>4</periodicity>
                </dosage>
            </pharm>
        </versions>
    </medicine>

    <medicine name="Flagyl">
        <group>antibiotic</group>
        <analogs>Metronidazole</analogs>
        <analogs>Abozole</analogs>
        <analogs>Ambizole</analogs>
        <versions version="TABLET">
            <pharm name="Pfizer">
                <certificate id="789">
                    <startDate>1970-03-15</startDate>
                    <expirationDate>2025-03-15</expirationDate>
                    <registrationOrganization>FDA</registrationOrganization>
                </certificate>
                <package>
                    <type>BLISTER</type>
                    <amount>50</amount>
                    <price>45800</price>
                </package>
                <dosage>
                    <number>1</number>
                    <periodicity>2</periodicity>
                </dosage>
            </pharm>
            <pharm name="PLIVA">
                <certificate id="15620">
                    <startDate>1980-03-15</startDate>
                    <expirationDate>2030-03-15</expirationDate>
                    <registrationOrganization>FDA</registrationOrganization>
                </certificate>
                <package>
                    <type>BLISTER</type>
                    <amount>25</amount>
                    <price>25600</price>
                </package>
                <dosage>
                    <number>1</number>
                    <periodicity>3</periodicity>
                </dosage>
            </pharm>
        </versions>

        <versions version="CAPSULE">
            <pharm name="PLIVA">
                <certificate id="15619">
                    <startDate>1980-03-15</startDate>
                    <expirationDate>2030-03-15</expirationDate>
                    <registrationOrganization>FDA</registrationOrganization>
                </certificate>
                <package>
                    <type>BLISTER</type>
                    <amount>50</amount>
                    <price>25600</price>
                </package>
                <dosage>
                    <number>2</number>
                    <periodicity>2</periodicity>
                </dosage>
            </pharm>
        </versions>
    </medicine>
</medicines>
